[workspace]
resolver = "2"
members = [ "axum-dependencies","examples/basic-*"]

[workspace.package]
version = "0.1.0"
authors = ["malikeljaouadi@gmail.com"]
edition = "2021"
publish = false

[profile.release]
codegen-units = 1
lto = true
